name: MERN CI

on:
  push:
    branches: [main]

jobs:
  mongo-init:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Wait for MongoDB to be ready
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
          echo "MongoDB is up"

      - name: Seed MongoDB
        working-directory: ./Backend
        run: |
          npm install
          node seedTodoData.js

  test:
    runs-on: ubuntu-latest
    needs: mongo-init

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Installing Dependencies
        working-directory: ./Backend
        run: npm install

      - name: Running Backend tests
        working-directory: ./Backend
        run: npm test 

